<?php namespace ProcessWire;

class MediaLister extends WireData implements Module {

	/**
	 * Module information
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Media Lister: Hooks',
			'summary' => 'Hooks for Media Lister.',
			'version' => '0.1.0',
			'author' => 'Robin Sallis',
			'href' => 'https://github.com/Toutouwai/ProcessMediaLister',
			'icon' => 'th-large',
			'autoload' => 'template=admin',
			'requires' => 'ProcessWire>=3.0.0, PHP>=7.0.0, ProcessMediaLister',
		);
	}

	protected $open;

	/**
	 * Ready
	 */
	public function ready() {
		$this->addHookBefore('ProcessPageEdit::execute', $this, 'beforePageEdit');
		$this->addHookAfter('ProcessPageEdit::execute', $this, 'afterPageEdit');
	}

	/**
	 * Before ProcessPageEdit::execute
	 *
	 * @param HookEvent $event
	 */
	protected function beforePageEdit(HookEvent $event) {
		if($this->wire()->config->ajax) return;
		$open_ids = $this->wire()->sanitizer->intArray($this->wire()->input->get('pml_open'));
		if(!$open_ids) return;
		$session = $this->wire()->session;
		$session->setFor('InputfieldRepeater', 'openIDs', $open_ids);
		$session->setFor('InputfieldRepeaterMatrix', 'openIDs', $open_ids);
		$this->open = true;
	}

	/**
	 * After ProcessPageEdit::execute
	 *
	 * @param HookEvent $event
	 */
	protected function afterPageEdit(HookEvent $event) {
		if(!$this->open) return;
		$session = $this->wire()->session;
		$session->setFor('InputfieldRepeater', 'openIDs', []);
		$session->setFor('InputfieldRepeaterMatrix', 'openIDs', []);
	}

}
